### ISSUE TITLE
Privacy icon for Disqus misplaced

### ISSUE THREAD

**Issue by kekearif** [AWEEKJ/Kiko-plus#4]
Hey, just trying to integrate Disqus into my blog. When I view the blog on my iPhone 6 the bottom icons are like so:
![img_0322](https://cloud.githubusercontent.com/assets/10420186/19811581/946bf462-9d64-11e6-9098-0a0cf8d0f693.PNG)

The privacy icons is misaligned. Just wondered if you had stumbled on this issue before and know if there's a fix or not? Looks like there isn't enough width. Maybe there is somewhere I can modify the width of the blog? Thanks

**Comment by aweekj** [comment]
Modify layout `.content-container` padding in `_site.scss`.

```css
.content-container {
  max-width: 38rem;
  padding: 2rem 1.3rem;
  margin-left:  auto;
  margin-right: auto;

  @media (min-width: 38rem){
    padding: 5rem 1rem;
  }
}
```

Check out [here](https://github.com/AWEEKJ/Kiko-plus/commit/c9ed74f4fc3176fbd3af3569890cebe2a2242f75).
